// Code generated by mfd-generator v0.6.0; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	Event struct {
		ID, UserTgID, Message, SendAt, CreatedAt string
	}
}{
	Event: struct {
		ID, UserTgID, Message, SendAt, CreatedAt string
	}{
		ID:        "eventId",
		UserTgID:  "userTgId",
		Message:   "message",
		SendAt:    "sendAt",
		CreatedAt: "createdAt",
	},
}

var Tables = struct {
	Event struct {
		Name, Alias string
	}
}{
	Event: struct {
		Name, Alias string
	}{
		Name:  "events",
		Alias: "t",
	},
}

type Event struct {
	tableName struct{} `pg:"events,alias:t,discard_unknown_columns"`

	ID        int       `pg:"eventId,pk"`
	UserTgID  int64     `pg:"userTgId,use_zero"`
	Message   string    `pg:"message,use_zero"`
	SendAt    time.Time `pg:"sendAt,use_zero"`
	CreatedAt time.Time `pg:"createdAt,use_zero"`
}
